### ISSUE TITLE
Contacter l'équipe

### ISSUE THREAD

**Issue by Monost0ne** [WildCodeSchool/blog-e-boulga#6]
### Narration
ETQ User je désire avoir des informations ou pouvoir contacter l'équipe, afin de donner un feedback

### Spec
CF contact:
https://www.figma.com/file/JEkawmwKmoZYk3KUIOhL3K/Wild-BlogeBoulga?type=design&node-id=0-1&mode=design&t=3PBBpsBBnXfJA56y-0

Création d'un formulaire : 

- Votre prénom
- Votre nom
- Votre adresse email
- Sujet de votre message
- Votre message
- Accord du User

TOUS les champs doivent être remplis.
Si on est chaud on fera un check sur le format de l'adresse mail /o/
Validation fake de l'envoie du server => Success message

Success message "Nous vous remercions pour votre message"
Fail message "Vous n'avez pas rempli le formulaire correctement"

### Hors scope
Navigation
Gestion du form réelle par envoie

### SubTask

- [ ] Vérification des champs non vides
- [ ] Vérification du format de l'adresse mail
- [ ] Validation fake du form

Desktop

- [x] Intégration form
- [x] Intégration bloc de droite

Mobile

- [x] Intégration form
- [x]  Intégration bloc du dessus

### Critère d'acceptante
Given I am a User,
And I am on the "Contact us" page,
And I fill all the field with correct data
When I click on the CTA,
Then I can see a success message

Given I am a User,
And I am on the "Contact us" page,
And I forget to fill all the field with correct data
When I click on the CTA,
Then I can see a fail message

Given I am a User,
And I am on the "Contact us" page,
And I fill all the field with data
And I fill the mail field without an '@'
When I click on the CTA,
Then I can see a fail message

### Images
Desktop
![Image](https://github.com/WildCodeSchool/blog-e-boulga/assets/45230586/80a1a2f2-6418-4c03-b89a-61ebbaf1d863)

Mobile
![Image](https://github.com/WildCodeSchool/blog-e-boulga/assets/45230586/ddeb9dbf-ee21-4d72-a04d-bb07ac4eb29b)
